name: lofime
description: A new Jaspr project
version: 0.0.1
publish_to: none


environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  dart_mappable: ^4.6.1
  jaspr: ^0.22.0
  jaspr_lucide:
    git: https://github.com/Shreemanarjun/jaspr_lucide.git
  jaspr_riverpod: ^0.4.2
  jaspr_router: ^0.8.1
  talker: ^5.1.9
  talker_riverpod_logger: ^5.1.9
  universal_web: ^1.1.1
  youtube_explode_dart: ^3.0.5
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.10.4
  build_web_compilers: ^4.4.6
  jaspr_builder: ^0.22.0
  jaspr_lints: ^0.6.0
  jaspr_test: ^0.22.0
  lints: ^6.0.0
  jaspr_tailwind: ^0.3.5
  dart_mappable_builder: ^4.6.3

jaspr:
  mode: client
